name: Coverage
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Running tests
        run: |
          pip install coverage
          coverage run -m unittest discover test
          coverage xml --include='./src/**'
      - name: Get Coverage
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 1
